name: OrleansMC
author: MustqfaCan
description: OrleansMC Ana Plugini
version: 0.1
main: com.orleansmc.bukkit.OrleansMC
api-version: '1.21'
depend: [PlaceholderAPI, LuckPerms, ProtocolLib, helper, HuskHomes]
permissions:
  orleansmc.admin:
    description: Admin yetkisi
    default: op
  "orleansmc.custom_join_sound":
    description: Giriş sesi
    default: op
  "orleansmc.custom_join_message":
    description: Giriş mesajı
    default: op
  "orleansmc.join_notification":
    description: Giriş bildirimi
    default: op